### ISSUE TITLE
Issue: Save and Update in settings is not working

### ISSUE THREAD

**Issue by arkham42** [matthewpennell/eve-traders-handbook#10]
I try to remove systems from monitoring then hit save and update. When the screen is refreshed the same systems are still there. 

+----+---------------------------+-----------------------------++---------------------+---------------------+
| id | key                       | label                       || created_at          | updated_at          |
+----+---------------------------+-----------------------------++---------------------+---------------------+
|  1 | api_key_id                | Key ID                      || 0000-00-00 00:00:00 | 2015-05-11 19:02:50 |
|  2 | api_key_verification_code | Verification Code           || 0000-00-00 00:00:00 | 2015-05-11 19:02:50 |
|  3 | api_key_character_id      | Character                   || 0000-00-00 00:00:00 | 2015-05-11 19:03:13 |
|  4 | home_region_id            | Home Region                 || 0000-00-00 00:00:00 | 2015-05-11 19:04:18 |
|  5 | alliances                 | Alliances (comma-separated) || 0000-00-00 00:00:00 | 2015-05-11 19:04:18 |
|  6 | systems                   | Systems (comma-separated)   || 0000-00-00 00:00:00 | 2015-05-11 19:04:18 |
+----+---------------------------+-----------------------------++---------------------+---------------------+

**Comment by arkham42** [comment]
Also it appears that prices are not updating either. I'm still seeing data from 2 days ago when i select an item.

**Comment by matthewpennell** [comment]
Removing systems is working for me. Do you have any systems entered at the moment - do they show up in the darker grey boxes below the systems field? Are you able to share the current value in your settings table? The structure you pasted is missing the value column for some reason.

**Comment by matthewpennell** [comment]
Re. prices - the API call checks whether the last poll was less than an hour ago - see https://github.com/matthewpennell/eve-traders-handbook/blob/master/app/classes/ETH/API.php from line 43.

You can check what is going on by adding after line 48:

echo "Found a cached price for type ID $type\n";

That will tell you if it is incorrectly flagging all prices as cached - perhaps your MySQL version isn't dealing with the time difference calculation properly.
