### ISSUE TITLE
Request : Password page

### ISSUE THREAD

**Issue by DragonHelm** [matthewpennell/eve-traders-handbook#11]
We have this installed on our corp site however it shows the settings page to everyone and allows the API to be seen. If possible could you add a simple password request to access the settings page, or not show the API in full, allow the password to be set within the password page to make it easy. 

Many thanks and excellent project

**Comment by matthewpennell** [comment]
I don't want to add another layer of security for the settings page since it would not be helpful for the majority of people running it as individuals. What you could easily do instead is add a password requirement to that URL on your server using .htaccess/.htpasswd.
