### ISSUE TITLE
Unable to find 'import' folder

### ISSUE THREAD

**Issue by Gokuofuin** [matthewpennell/eve-traders-handbook#13]
Hi there

In the last step you say we need to navigate to 'import/zkillboard' now my installation has no such folder. So any thoughts?

**Comment by Nothing4You** [comment]
Are you using apache?
If yes, do you have .htaccess files enabled?

In my lighttpd install I had to do some custom rewrite rules due to lack of .htaccess support.

**Comment by Gokuofuin** [comment]
To be honest with you I do not know, I do have HTaccess files though in my other installations so I would assume I have apache and HTaccess support, though I do not have any .htaccess file inside of the traders folder

**Comment by Nothing4You** [comment]
In the git repo there's a .htaccess file in the [public](https://github.com/matthewpennell/eve-traders-handbook/tree/master/public) folder

**Comment by Gokuofuin** [comment]
Ah yes I have that, though I don't see how that helps me :) Cus I still have no import folder?

**Comment by Nothing4You** [comment]
It's not a real folder, it's a virtual routed path handled by index.php.

**Comment by Gokuofuin** [comment]
mmmm ok well then I am fresh out of ideas, because if I try to navigate to the indended address of 'website.com/import/zkillboard' then I get the 404 not found page?

**Comment by matthewpennell** [comment]
Yes, as @Nothing4You says, "navigate" means using your browser - so you go to mysite.com/import/zkillboard. If you're getting a 404 for that URL, then something is not working with your rewrite rules.

**Comment by Gokuofuin** [comment]
Any thoughts on how to diagnose what the problem is with the rewrite rules?

**Comment by matthewpennell** [comment]
Does the main application work okay when you visit yoursite.com/index.php? If not, then something in your configuration is wrong, possibly you have not pointed the web server at the /public/ folder.

If the main index.php homepage does work, then your [.htaccess](https://github.com/matthewpennell/eve-traders-handbook/blob/master/public/.htaccess) file is not being processed properly. Maybe you don't have mod_rewrite installed - try visiting phpinfo.php under your localhost and search for "mod_rewrite" to see if anything there might indicate what is not working.

**Comment by Gokuofuin** [comment]
-> http://evetrader.dantecampbell.org/index.php

Works fine like that, just doesn't work when I try to import thing.

**Comment by matthewpennell** [comment]
http://evetrader.dantecampbell.org/import/zkillboard

This page gives me a "Whoops" error message, not the 404 that you claimed, so that means it's not the rewrite rules but something wrong in the application.

SSH to your server, navigate to the root of the app, then run _tail -f app/storage/logs/laravel.log_ and see what error(s) you get when you load the above URL.

**Comment by devilswin** [comment]
I am having the same issue with importing the zkill
