### ISSUE TITLE
"Whoops, looks like something went wrong" when importing zkillboard

### ISSUE THREAD

**Issue by devilswin** [matthewpennell/eve-traders-handbook#16]
The main site works perfectly, the only issue is that I get this message when going to eve-traders-handbook.com/import/zkillboard

My main site is eve-traders-handbook.com. The port I use for MaMp is 80

**Comment by matthewpennell** [comment]
Have you set your settings correctly, including your API key and chosen system/region/alliance? It won't work without that information.

You can get a more detailed stacktrace by looking at the log output, which is saved to app/storage/logs/laravel.php. Try the import again, then paste the last full set of output from the end of that file here.

**Comment by devilswin** [comment]
Here is the logs:

> #16 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
> #17 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
> #18 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
> #19 {main} [] []

**Comment by devilswin** [comment]
Also, Is it an issue that I am in a wormhole corp? And I selected a Wormhole region?

**Comment by matthewpennell** [comment]
You need to post more lines of your log, starting with the line that starts something like this:

`[2016-06-26 16:05:25] production.ERROR: exception`

It might be WH related, I didn't even know there were wormhole regions...

**Comment by devilswin** [comment]
> #11 {main} [] []
> [2016-07-06 11:22:08] production.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
> Stack trace:
> #0 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1049): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
> #1 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1017): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
> #2 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #3 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #4 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
> #5 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
> #6 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
> #7 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
> #8 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
> #9 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
> #10 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
> #11 {main} [] []
> [2016-07-06 11:24:35] production.ERROR: ErrorException: Invalid argument supplied for foreach() in /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php:80
> Stack trace:
> #0 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php(80): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/Users/GO/Deskt...', 80, Array)
> #1 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php(50): ImportController->getZkillboard('31000355,310003...')
> #2 [internal function]: ImportController->getZkillboard()
> #3 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
> #4 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getZkillboard', Array)
> #5 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ImportController), Object(Illuminate\Routing\Route), 'getZkillboard')
> #6 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ImportControlle...', 'getZkillboard')
> #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
> #8 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
> #9 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
> #10 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #11 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #12 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
> #13 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
> #14 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
> #15 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
> #16 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
> #17 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
> #18 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
> #19 {main} [] []
> [2016-07-06 11:24:39] production.ERROR: ErrorException: Invalid argument supplied for foreach() in /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php:80
> Stack trace:
> #0 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php(80): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/Users/GO/Deskt...', 80, Array)
> #1 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php(50): ImportController->getZkillboard('31000355,310003...')
> #2 [internal function]: ImportController->getZkillboard()
> #3 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
> #4 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getZkillboard', Array)
> #5 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ImportController), Object(Illuminate\Routing\Route), 'getZkillboard')
> #6 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ImportControlle...', 'getZkillboard')
> #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
> #8 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
> #9 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
> #10 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #11 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #12 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
> #13 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
> #14 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
> #15 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
> #16 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
> #17 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
> #18 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
> #19 {main} [] []
> [2016-07-06 11:24:41] production.ERROR: ErrorException: Invalid argument supplied for foreach() in /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php:80
> Stack trace:
> #0 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php(80): Illuminate\Exception\Handler->handleError(2, 'Invalid argumen...', '/Users/GO/Deskt...', 80, Array)
> #1 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/ImportController.php(50): ImportController->getZkillboard('31000355,310003...')
> #2 [internal function]: ImportController->getZkillboard()
> #3 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
> #4 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getZkillboard', Array)
> #5 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ImportController), Object(Illuminate\Routing\Route), 'getZkillboard')
> #6 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ImportControlle...', 'getZkillboard')
> #7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
> #8 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
> #9 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
> #10 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #11 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #12 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
> #13 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
> #14 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
> #15 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
> #16 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
> #17 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
> #18 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
> #19 {main} [] []

**Comment by matthewpennell** [comment]
Okay, so it looks like when it is requesting the zkillboard data it is not getting any results back. It does work with WH systems - for example, here is a request showing all the Wingspan deaths in a WH system:

https://zkillboard.com/api/xml/losses/no-attackers/99006319/solarSystemID/31000355/

Do you have an alliance selected? Add this line to the app/controllers/ImportController.php, line 65:

`die($url);`

then reload the import/zkillboard page and tell me what it returns.

**Comment by devilswin** [comment]
This is what i get now: 

> https://zkillboard.com/api/xml/losses/no-attackers/allianceID/99006117/solarSystemID/31000355,31000356,31000357,31000358,31000359,31000360,31000361,31000362,31000363,31000364/

**Comment by matthewpennell** [comment]
Okay - so it seems there are no deaths by Ember Sands members in those systems. Let me patch the import code so it doesn't fail when there are zero kills returned.

**Comment by devilswin** [comment]
How u know that ;) But ok, ty

**Comment by matthewpennell** [comment]
Pushed a patch - if you pull the most recent changes and try again, it should now work.

**Comment by devilswin** [comment]
I just download the zip and copy paste it, since it didnt work when i used the git clone

**Comment by devilswin** [comment]
Will that work?

**Comment by matthewpennell** [comment]
Yes.

**Comment by devilswin** [comment]
Still didnt work, get the no attackers

**Comment by devilswin** [comment]
And now i get Whoops something went wrong when going to settings

**Comment by devilswin** [comment]
> [2016-07-06 11:52:52] production.ERROR: ErrorException: Trying to get property of non-object in /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/SettingsController.php:61
> Stack trace:
> #0 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/app/controllers/SettingsController.php(61): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/Users/GO/Deskt...', 61, Array)
> #1 [internal function]: SettingsController->getIndex()
> #2 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
> #3 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getIndex', Array)
> #4 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(SettingsController), Object(Illuminate\Routing\Route), 'getIndex')
> #5 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'SettingsControl...', 'getIndex')
> #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
> #7 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
> #8 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
> #9 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #10 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #11 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
> #12 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
> #13 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
> #14 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
> #15 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
> #16 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
> #17 /Users/GO/Desktop/EveTools/TradingHandbook/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
> #18 {main} [] []

**Comment by matthewpennell** [comment]
You need to remove the debug line I asked you to add earlier. Also I just noticed I forgot to add a new row to the settings table, which I've now pushed. Try again - you will need to re-import the eth_database_setup.sql file.

**Comment by devilswin** [comment]
I get this error when trying to import the eth_database_setup.sql file 

#1062 - Duplicate entry '4' for key 'PRIMARY'

**Comment by devilswin** [comment]
Also, how do i reimport?

**Comment by matthewpennell** [comment]
Just delete the settings table first.

**Comment by devilswin** [comment]
Didnt work

**Comment by devilswin** [comment]
You used the number 4 twice for home_region_id and home_station_id

**Comment by matthewpennell** [comment]
Ah, whoops - fixed now, try again. :)

**Comment by devilswin** [comment]
It works now! But Since I am in a WH corp, should I add all regions, or what? since there is no real predefined area of operation

Edit: It worked w/o an API key somehow...

**Comment by devilswin** [comment]
I do get an error again when doing the zkillboard import: 

> No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No kills found in selected system(s). No response received from zKillboard API.

**Comment by matthewpennell** [comment]
I think that's due to making too many requests at once. There's a practical limit on how many regions it is appropriate to monitor at once; I never built it to check the whole of New Eden, so you have to decide whereabouts your alliance is most active, and just monitor those places.

Re. the API key - it's not used for the import, but you need it if you want accurate T2 invention calculations.

**Comment by devilswin** [comment]
Oh, I was using my main's api. Not my builders

**Comment by devilswin** [comment]
One issue I am having now is that I cant update my settings without it reverting

**Comment by matthewpennell** [comment]
What do you mean, reverting? You can always just empty the settings table if you're having issues with it, but let me know what is going wrong first.
