### ISSUE TITLE
"Whoops, looks like something went wrong" when entering settings

### ISSUE THREAD

**Issue by m4riuszb** [matthewpennell/eve-traders-handbook#17]
I get this message when I click to settings icon.
##### Log:

> [2016-07-07 12:11:25] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught TypeError: 
> Argument 1 passed to Illuminate\Exception>\WhoopsDisplayer::display() must be an instance of Exception, instance 
> of Error given, called in /opt/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Exception/Handler.php on line 280 
> and defined in /opt/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Exception/WhoopsDisplayer.php:43
> Stack trace:
> # 0 /opt/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(280): Illuminate\Exception\WhoopsDisplayer-display(Object(Error))
> # 1 /opt/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(159): Illuminate\Exception\Handler->>displayException(Object(Error))
> # 2 /opt/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(170): Illuminate\Exception\Handler->handleException(Object(Error))
> # 3 [internal function]: Illuminate\Exception\Handler->handleUncaughtException(Object(Error))
> # 4 {main}
> 
>  thrown in /opt/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Exception/WhoopsDisplayer.php:43
> Stack trace:
> # 0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
> # 1 {main} [] []
##### Server/Request Data:

| Header | Value |
| --- | --- |
| REDIRECT_STATUS | 200 |
| HTTP_HOST | 192.168.60.10 |
| HTTP_USER_AGENT | Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 |
| HTTP_ACCEPT | text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8 |
| HTTP_ACCEPT_LANGUAGE | en-US,en;q=0.5 |
| HTTP_ACCEPT_ENCODING | gzip, deflate |
| HTTP_REFERER | http://192.168.60.10/ |
| HTTP_COOKIE | laravel_session=eyJpdiI6IklmUEFMaG9ONjhTKzF6RGhjMlRqT3c9PSIsInZhbHVlIjoiUW1DbEU0ZVVxYUdHNm9YdXJoaktQeUsySEp5OXFJekl3M01MWU5UR2o5aFdJRjNhSXVrTXpxdmZta2drSTlQTTZ5QURuXC9JbGY2dGo2RUVKSk1MVVRRPT0iLCJtYWMiOiJjOTAyMTlmNzUzODI1ZWZiOWZiMDYwZTczZTM3YzM4YzA1MDFhNTU1NTUxN2UwMWMzZWYzYmQ5YTg1NWZjNWFjIn0%3D |
| HTTP_CONNECTION | keep-alive |
| PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |
| SERVER_SIGNATURE | <address>Apache/2.4.18 (Ubuntu) Server at 192.168.60.10 Port 80</address> |
| SERVER_SOFTWARE | Apache/2.4.18 (Ubuntu) |
| SERVER_NAME | 192.168.60.10 |
| SERVER_ADDR | 192.168.60.10 |
| SERVER_PORT | 80 |
| REMOTE_ADDR | 192.168.60.1 |
| DOCUMENT_ROOT | /opt/eve-traders-handbook/public |
| REQUEST_SCHEME | http |
| CONTEXT_PREFIX |  |
| CONTEXT_DOCUMENT_ROOT | /opt/eve-traders-handbook/public |
| SERVER_ADMIN | webmaster@localhost |
| SCRIPT_FILENAME | /opt/eve-traders-handbook/public/index.php |
| REMOTE_PORT | 45246 |
| REDIRECT_URL | /settings |
| GATEWAY_INTERFACE | CGI/1.1 |
| SERVER_PROTOCOL | HTTP/1.1 |
| REQUEST_METHOD | GET |
| QUERY_STRING |  |
| REQUEST_URI | /settings |
| SCRIPT_NAME | /index.php |
| PHP_SELF | /index.php |
| REQUEST_TIME_FLOAT | 1467893485.616 |
| REQUEST_TIME | 1467893485 |

**Comment by matthewpennell** [comment]
That's an error being thrown by Laravel, not by the app. Did you follow all of the instructions accurately in the installation guide? Does your server meet the minimum requirements?

**Comment by m4riuszb** [comment]
Ok, I have a wrong version of PHP (7.0.4) which is not compatible with version of laravel (4.2.x).

**Comment by matthewpennell** [comment]
Yeah, you'll need to downgrade to version 5.4 or thereabouts.
