### ISSUE TITLE
Issues with settings link

### ISSUE THREAD

**Issue by halo779** [matthewpennell/eve-traders-handbook#18]
Seems i'm having a few issues with the Settings link 404ing. Nothing jumps out at me as the cause as per your setup directions Although i am unfamiliar with Laravel PHP framework.

At first i suspected it to be rewrites not being changed to nginx formatting correctly However having fired up a fresh VM locally running a basic LAMP stack It seems that is not the case.

Here's an example link which is failing:
http://evetrade/eve-traders-handbook/public/settings

evetrade being the hostname of the VM i used for testing.

Suspect i have simply misunderstood something in the setup though?

**Comment by matthewpennell** [comment]
Sorry for the delay in replying, I've been on vacation. 

You shouldn't be using /public/ in your URLs, so your settings page should be here:

`http://evetrade/eve-traders-handbook/settings` (or even perhaps `http://evetrade/settings`)

In the VirtualHost setup you should have `evetrade` pointed to wherever you have the app installed, with `/public` at the end.

**Comment by halo779** [comment]
Not a problem on the delay.

Have now realised what wasn't right with my setup:
- Mod_rewrite was not active
- php curl extensions were not installed by default.

Likely worth noting for a clean linux installation!

The use of /public in my urls was to count out there being any issues with the virtualhost, I should have included that.
