### ISSUE TITLE
Whoops something went wrong

### ISSUE THREAD

**Issue by spicedandy** [matthewpennell/eve-traders-handbook#19]
Hi, I've looked everywhere for a fix to this before posting.  I've got the app loading using a symlink (had problems with both methods before I got the symlink to finally work) and I've configured the database.php.  I've tried the -chmod fix suggested in both the root application and the storage folder but I've still had no luck.  I don't know where to grab the error logs from and I can post those if they would help in identifying my problem.  I'm running osx with MAMP.

I've been trying to get this program to work all day and any help would be appreciated.  I'm very excited to try it out.  Thanks.

**Comment by ux4c** [comment]
The logs are in app/storage/logs/laravel.log. Watch the output there and paste the new output when you get the error page (I think the first line you want has a timestamp).

**Comment by matthewpennell** [comment]
The logs are in `app/storage/logs/laravel.log`. Watch the output there and paste the new output when you get the error page (I think the first line you want has a timestamp).

**Comment by spicedandy** [comment]
[2016-12-28 10:22:26] production.ERROR: ErrorException: Use of undefined constant ‘eve - assumed '‘eve' in /Users/race/Desktop/eve-traders-handbook/app/config/database.php:80
Stack trace:
#0 /Users/race/Desktop/eve-traders-handbook/app/config/database.php(80): Illuminate\Exception\Handler->handleError(8, 'Use of undefine...', '/Users/race/Des...', 80, Array)
#1 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(44): require('/Users/race/Des...')
#2 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Config/FileLoader.php(77): Illuminate\Filesystem\Filesystem->getRequire('/Users/race/Des...')
#3 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Config/Repository.php(152): Illuminate\Config\FileLoader->load('production', 'database', NULL)
#4 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Config/Repository.php(99): Illuminate\Config\Repository->load('database', NULL, '*::database')
#5 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Config/Repository.php(389): Illuminate\Config\Repository->get('database.defaul...')
#6 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(276): Illuminate\Config\Repository->offsetGet('database.defaul...')
#7 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(82): Illuminate\Database\DatabaseManager->getDefaultConnection()
#8 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(57): Illuminate\Database\DatabaseManager->parseConnectionName(NULL)
#9 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(321): Illuminate\Database\DatabaseManager->connection()
#10 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Database\DatabaseManager->__call('select', Array)
#11 /Users/race/Desktop/eve-traders-handbook/app/controllers/MasterController.php(19): Illuminate\Support\Facades\Facade::__callStatic('select', Array)
#12 [internal function]: MasterController->home()
#13 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('home', Array)
#15 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(MasterController), Object(Illuminate\Routing\Route), 'home')
#16 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'MasterControlle...', 'home')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#25 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#26 /Users/race/Desktop/eve-traders-handbook/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#27 /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#28 /Users/race/Desktop/eve-traders-handbook/public/index.php(49): Illuminate\Foundation\Application->run()
#29 {main} [] []

**Comment by spicedandy** [comment]
Is this a problem with the database name?

**Comment by spicedandy** [comment]
Ok, I think the problem was related to the ' character, which I replaced and now I get a completely new error with the eth database:
[2016-12-28 10:37:40] production.ERROR: PDOException: SQLSTATE[HY000] [1049] Unknown database 'eth' in /Users/race/Desktop/eve-traders-handbook/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47

**Comment by matthewpennell** [comment]
Yes, you had a 'magic' quote in the database config, which can happen sometimes if you copy/paste from a tutorial or article.

The new error is pretty self-explanatory - you don't have a database named "eth", which is what your config is looking for. Work through Step 4 of the [installation instructions](https://github.com/matthewpennell/eve-traders-handbook/wiki/Installation) and you should be okay.

**Comment by spicedandy** [comment]
I renamed the mysql database to my database name and the app loaded.  I had entered the name in the sqlsrv database.  For clarification, do i need to have the name/user/pw set for the sqlsrv, or should it be left alone etc?  Otherwise thanks for your help.

**Comment by matthewpennell** [comment]
No, you only need to enter the details for the mysql connection, as that's what you're using.
