### ISSUE TITLE
ZKillboard JSON parser not working

### ISSUE THREAD

**Issue by mossyblog** [matthewpennell/eve-traders-handbook#20]
This is from the logs whenever i do /import/zkillboard

[2017-02-07 07:50:33] production.ERROR: exception 'Exception' with message 'Unable to parse response as JSON' in C:\xampp\htdocs\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Handlers\JsonHandler.php:29
Stack trace:
#0 C:\xampp\htdocs\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Response.php(106): Httpful\Handlers\JsonHandler->parse('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x03$\x8BA\x0E\xC2...')
#1 C:\xampp\htdocs\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Response.php(45): Httpful\Response->_parse('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x03$\x8BA\x0E\xC2...')
#2 C:\xampp\htdocs\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Request.php(229): Httpful\Response->__construct('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x03$\x8BA\x0E\xC2...', 'HTTP/1.1 200 OK...', Object(Httpful\Request), Array)
#3 C:\xampp\htdocs\eve-traders-handbook\app\controllers\ImportController.php(70): Httpful\Request->send()
#4 C:\xampp\htdocs\eve-traders-handbook\app\controllers\ImportController.php(50): ImportController->getZkillboard('30003565,300035...')
#5 [internal function]: ImportController->getZkillboard()
#6 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getZkillboard', Array)
#8 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ImportController), Object(Illuminate\Routing\Route), 'getZkillboard')
#9 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ImportControlle...', 'getZkillboard')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\xampp\htdocs\eve-traders-handbook\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\eve-traders-handbook\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

**Comment by mossyblog** [comment]
When I echoed back the result from $body in handler i got this aswell:

�$�A�0���	���3���+j)�[;!���8��w��Z��u�V�����
!�=؇�
������kB��Fl������K�c���(�Ce9����������z

**Comment by matthewpennell** [comment]
Thanks for the report, I will look into it.

**Comment by matthewpennell** [comment]
Looks like zKillboard has started requiring system IDs to be submitted in numerical order. I've pushed a fix, so if you update your code it should work now.
