### ISSUE TITLE
Import zKillboard

### ISSUE THREAD

**Issue by IPFR33LY** [matthewpennell/eve-traders-handbook#21]
When navigating to http://localhost:8888/eve-traders-handbook/public/import/zkillboard, I get a "Whoops, looks like something went wrong".

I couldn't figure out why this would happen, any ideas?

**Comment by matthewpennell** [comment]
You shouldn't need the `/public` path in your URL - it should be set as the root of the site or VirtualDomain. It looks like maybe you skipped Step 3 in the installation instructions.
