### ISSUE TITLE
Zkillboard importing

### ISSUE THREAD

**Issue by Osakabachi** [matthewpennell/eve-traders-handbook#22]
Step 5:  "Finally, do the same with star systems."   
The app does not give an immediate option for star systems, but for regions instead.  Is there something that I've missed here?

Step 6:  http://localhost/eve-traders-handbook/import/zkillboard gives an oops message.  (windows install, and localhost:80 simply shortens the url to localhost, and gives the same result)

Everything else up to this point works fine, but I am by no means an expert with these matters, so it's entirely possible that I've missed something.

**Comment by matthewpennell** [comment]
Step 5: I updated it to use regions instead of systems a while ago; thanks, I'll update the installation instructions too.

Step 6: You need to see what error is being thrown. Load the page with the error, then check the log at `app/storage/logs/laravel.log` - the last set of entries (starting with a timestamp) should give you a clue to what the problem is. Post the errors if you can't tell what us causing the error.

**Comment by Osakabachi** [comment]
Well, I've had a look at the files referenced by the error log, and I'm admittedly out of my element and can't make heads or tails of it:


[2017-02-27 00:46:02] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:148
Stack trace:
#0 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1049): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1017): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\xampp\htdocs\eve-traders-handbook\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\eve-traders-handbook\public\index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []

**Comment by matthewpennell** [comment]
That looks like a routing issue, which would suggest you haven't got the app set up in the right location. Does the root `http://localhost/eve-traders-handbook/` page load properly? Also try the ` http://localhost/eve-traders-handbook/settings` page to see if that loads.

**Comment by farshadsharifjob** [comment]
vendor\illuminate\database\Connectors\Connector.php:55 Stack trace: #0

**Comment by Osakabachi** [comment]
Alright, neither of those two pages loaded properly, so on the basis that the app was mislocated, I've started over from scratch, following your instructions, and basically documented the process...  maybe you can point me to where I've gone wrong.

-Installed XAMPP - http://localhost opens XAMPP dashboard no problem.
-Extracted ETH zip file to D:\eve-traders-handbook-master  ; renamed folder to eve-traders-handbook
-Edited httpd-vhosts.conf - added supplied code, uncommented NameVirtualHost *:80
-Changed code to read:
<VirtualHost *>
  ServerName eve-traders-handbook
  DocumentRoot "D:\eve-traders-handbook\public"
  DirectoryIndex index.php
  <Directory "D:\eve-traders-handbook\public">
    AllowOverride all
  </Directory>
</VirtualHost>
-Saved file, restarted apache.
-Added "127.0.0.1    eve-traders-handbook" to C:\Windows\System32\drivers\etc\hosts & saved file in administrator mode.
-Http://eve-traders-handbook/  now directs to an access forbidden page:  http://prntscr.com/efrw15  (screenshot)

--trying 3a instead of 3b.
-commented out the added code in httpd-vhosts.conf and recommented NameVirtualHost *:80  ; saved file & restarted apache.

-Copied eve-traders-handbook folder from D:\ to C:\xampp\htdocs\
-did not comment out the change to etc\hosts file.
-http://localhost/eve-traders-handbook/ now opens the index of /eve-traders-handbook    http://prntscr.com/efrz0m  (screenshot)

-Seeing as how the virtual host code in step 3b points to the public sub-folder, I assume that we're checking http://localhost/eve-traders-handbook/public.  Navigating to this URL does display the whoops message.

-Navigated to http://localhost/phpmyadmin
-Created new database named "manuf" with utf8_unicode_ci collation.
-Imported files listed from fuzzwork
-Imported eth_database_setup.sql
-Edited lines 58-60 of database.php : 
'database'  => 'manuf',
'username'  => 'root',
'password'  => '',
Saved file.

-Navigating to http://localhost/eve-traders-handbook/public/  now properly displays the app.

-Input information as outlined in step 5; Navigated back to main app page.

-http://localhost/eve-traders-handbook/import/zkillboard/ brings up an "object not found" 404 error for localhost.     http://prntscr.com/efs6om

-http://localhost/eve-traders-handbook/public/import/zkillboard shortens the URL to "http://localhost/import/zkillboard" and brings the same 404 error.


And that's pretty much where I've lost the rabbit.  Again, I'm sorry that this is basically a novice's effort to understand something very far over my head.

**Comment by matthewpennell** [comment]
Where you're going wrong is setting the root of the site. Because you're relying on `/public` being in the path to load it, you need to include that in all the URLs: 

`http://localhost/eve-traders-handbook/public/import/zkillboard/`

However, that's not really optimal. What I would recommend is putting the code somewhere else, and then creating a symlink from `C:\xampp\htdocs` that points to the `/public` folder wherever your code lives. I don't use Windows, but according to [this article](http://lifehacker.com/5496652/how-to-use-symlinks-in-windows) you should be able to run something like this in cmd:

`mklink /j "C:\xampp\htdocs\eve-traders-handbook" D:\eve-traders-handbook\public`

**Comment by Osakabachi** [comment]
Alright, setting up the symlink gets me to step 6, importing from zkillboard.

running http://localhost/eve-traders-handbook/import/zkillboard/  gives me a 404 localhost error

EDIT::  OK, so for the import bit, it looks like the port is required in the URL.  This threw me off because for the entirety of the process up to this point it has not been needed.

It looks though as if it's working now!  Thanks very much for the assist!

**Comment by matthewpennell** [comment]
That's strange, since the port is either required or not (as it default to 80 if no port is specified). Glad it's working for you now, though.
