### ISSUE TITLE
Zkillboard import

### ISSUE THREAD

**Issue by retsuc** [matthewpennell/eve-traders-handbook#23]
Whenever I do a /import/zkillboard the log kicks out

[2017-06-21 07:57:49] production.ERROR: exception 'Exception' with message 'Unable to parse response as JSON' in C:\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Handlers\JsonHandler.php:29
Stack trace:
#0 C:\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Response.php(106): Httpful\Handlers\JsonHandler->parse('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x03$\x8BA\x0E\xC2...')
#1 C:\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Response.php(45): Httpful\Response->_parse('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x03$\x8BA\x0E\xC2...')
#2 C:\eve-traders-handbook\vendor\nategood\httpful\src\Httpful\Request.php(229): Httpful\Response->__construct('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x03$\x8BA\x0E\xC2...', 'HTTP/1.1 200 OK...', Object(Httpful\Request), Array)
#3 C:\eve-traders-handbook\app\controllers\ImportController.php(73): Httpful\Request->send()
#4 C:\eve-traders-handbook\app\controllers\ImportController.php(53): ImportController->getZkillboard('30001153,300011...')
#5 [internal function]: ImportController->getZkillboard()
#6 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#7 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getZkillboard', Array)
#8 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(ImportController), Object(Illuminate\Routing\Route), 'getZkillboard')
#9 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'ImportControlle...', 'getZkillboard')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#12 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\eve-traders-handbook\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 c:\eve-traders-handbook\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

**Comment by matthewpennell** [comment]
It's not getting the correct format of response back from zKillboard. Have you gone through the steps to enter your alliance, home region, and the regions where you want to collect kills?

**Comment by retsuc** [comment]
Yes, I've entered all that information.  I tried again this morning, i got the "Whoops" message again, but when i reloaded ETH main page all the info was there despite that.  It didn't do that last night

**Comment by retsuc** [comment]
Its just acting odd.  Sometimes it will work, most times it won't.  Same with import/clear.  Sometimes it gives the whoops and clears, sometimes I get a 404 error.

edit: I found the clear problem.  the link points to http://localhost/import/clear instead of http://localhost/eve-traders-handbook/import/clear

edit2: The import issue seems to be if you have more than one alliance selected.  I was hoping to pull data from a couple of them.  Additionally, it will import and give the Whoops message, but when you reload the main page the data is there.  Everytime I add a second alliance, it won't import.

**Comment by ghost** [comment]
I'm not sure if the zKill API supports multiple alliances. You can check by adding a line to `app/controllers/ImportController.php` around line 68:

`die($url);`

That will spit out the zkillboard call it is making. Try visiting that URL; if you get an API error, it's because zKill doesn't allow multiple alliances to be submitted.

Let me know and I'll fix it to not permit selecting more than one alliance.

**Comment by retsuc** [comment]
This is the output I got when i added that

https://zkillboard.com/api/xml/losses/no-attackers/allianceID/1354830081,498125261/solarSystemID/30001153,30001154,30001155,30001156,30001157,30001158,30001159,30001160,30001161,30001162/

**Comment by ux4c** [comment]
Ah, it needs the alliance IDs to be in numerical order. Just a sec, I'll push a patch to fix that.

**Comment by ux4c** [comment]
Pushed https://github.com/matthewpennell/eve-traders-handbook/commit/7e7a8ba2deb555edf8682e2cf4861100ba079127 which fixes the bug you are encountering.

**Comment by matthewpennell** [comment]
Pushed https://github.com/matthewpennell/eve-traders-handbook/commit/7e7a8ba2deb555edf8682e2cf4861100ba079127 which fixes the bug you were encountering.

**Comment by retsuc** [comment]
Thanks
