### ISSUE TITLE
Unable to reach settings page

### ISSUE THREAD

**Issue by Rayvenhaus** [matthewpennell/eve-traders-handbook#24]
I've just installed handbook on a Ubuntu 16.04 system that I have several other Eve related applications running on, most notably AllianceAuth.

I've followed the setup instructions, got the "Whoops, something's gone wrong page" and finished installing and setting up. I now see the main page of Eve Traders Handbook just fine, however, when I click on the Settings gear icon, I get the following.

A blank page that displays:  
Not Found

The requested URL /eve-traders-handbook/public/index.php was not found on this server.

Here's my Virtual Host setting in my Apache Conf file:
        Alias /handbook /var/www/html/eve-traders-handbook/public
        <Directory "/var/www/html/eve-traders-handbook/public">
            DirectoryIndex index.php
            AllowOverride all
        </Directory>

No log files created by the application. Apache log files show this:
173.81.238.183 - - [06/Jul/2017:11:02:25 +0000] "GET /handbook/ HTTP/1.1" 200 5518 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:25 +0000] "GET /handbook/c/normalize.css HTTP/1.1" 200 3049 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:25 +0000] "GET /handbook/c/vendor/jquery-ui.min.css HTTP/1.1" 200 4458 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:25 +0000] "GET /handbook/c/eth.css HTTP/1.1" 200 5471 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:26 +0000] "GET /handbook/j/eth.js HTTP/1.1" 200 5301 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:26 +0000] "GET /handbook/j/vendor/jquery-ui.min.js HTTP/1.1" 200 15688 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:26 +0000] "GET /handbook/j/vendor/jquery-2.1.1.min.js HTTP/1.1" 200 33255 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:26 +0000] "GET /handbook/i/fits.png HTTP/1.1" 200 2078 "https://www.thedoubled.org/handbook/c/eth.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:26 +0000] "GET /handbook/i/background.jpg HTTP/1.1" 200 36997 "https://www.thedoubled.org/handbook/c/eth.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:26 +0000] "GET /handbook/i/settings.png HTTP/1.1" 200 1217 "https://www.thedoubled.org/handbook/c/eth.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:27 +0000] "GET /favicon.ico HTTP/1.1" 200 1508 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:02:28 +0000] "GET /handbook/settings HTTP/1.1" 404 446 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
173.81.238.183 - - [06/Jul/2017:11:08:35 +0000] "GET /handbook/settings HTTP/1.1" 404 3648 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"

**Comment by matthewpennell** [comment]
I suspect it's because your `Alias` line in Apache conf isn't working properly. [This SO post](https://stackoverflow.com/questions/15770778/configure-apache-conf-for-alias) seems to indicate that maybe you need to include all directives inside the `<Directory>` block.

**Comment by Rayvenhaus** [comment]
I've set up the apache2 conf file as directed.  I can get to the front page just fine, everything works to land there. It's that when I click on the gear icon to get to the settings page, I get a 404 error:

173.81.238.183 - - [07/Jul/2017:19:24:45 +0000] "GET /handbook/settings HTTP/1.1" 404 727 "https://www.thedoubled.org/handbook/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"

Everything was included inside the >Directory> block, I just didn't paste the closing </Directory> line when I copied it here

**Comment by matthewpennell** [comment]
Sorry, I don't know that much about Apache configuration, and I never tried running the app using `Alias` to direct traffic to a different location. I have found this page, which sounds like the exact problem you're having:

https://stackoverflow.com/questions/17647825/apache-trying-to-load-from-documentroot-instead-of-alias-directory

Maybe try adding/removing some of the settings under the `<Directory>` and see if anything works?

**Comment by Nilitys** [comment]
Hi, I also have an issue to reach the setting page/app page.

First I'd like to say the I'm a noob in every tools used here, but I know how to follow a step by step process. yet, I'm stuck at the end of step 4 and cant find the app.

I'm on windows 7, I did step 3a where I copied the ETH folder in htdocs folder.
I've got the "http://localhost:8888/eve-traders-handbook/" page as an "index of/" page

I did the step 4 with the database without any issues, even so I dont know which "Whoops" page I'm supposed to be on, since I got multiple available in the "index of/" pages.

Therefore, I still dont know which page I'm supposed to be on at the end of step 4 and the "index of/" page is unchanged.

could someone let me know what I've missed please?

**Comment by matthewpennell** [comment]
@Nilitys - If you're seeing the `Index of /` file list at your URL, that means that either your URL is not pointing correctly to the root of the application, or the `.htaccess` file is not correctly serving the `index.php` page.

What do you see listed on the page? If it is the app/bootstrap/public/vendor folders and files, try clicking into the `public` directory - that is where all requests are served from.

**Comment by Nilitys** [comment]
ok, the "public" folder is indeed a "whoops" page.

about the ".htaccess" file (in C:\xampp\htdocs\eve-traders-handbook\public), here is it's content:

"<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>"


shall I change the "{REQUEST_FILENAME}" to something else?

**Comment by matthewpennell** [comment]
No, that's fine. `/public` is where the site is viewed, although I'm not 100% sure it will work as intended if you're just viewing it directly.

To diagnose the issue you're still having, have a look at the `app/storage/logs/laravel.log` file - the latest errors are at the end of the file. It should give you an idea what specific part is not working.

**Comment by Nilitys** [comment]
I do not have a "laravel.log" at that location, only a ".gitignore"

**Comment by ogabrielluiz** [comment]
I'm having the same issue as Nilitys.

I found out that when I clicked on public I got the Whoops page but no matter what I do, it won't change from that.

I tried both methods, the second one when I put the url it takes me to the dashboard.
The first one is the one I get the "Whoops.." page.

The database seems to be setup told to. 

Any tips? Could be PHP's version?

**Comment by matthewpennell** [comment]
@samygabriel - could be. This application is now several years old, and will no longer work as intended due to zKillboard removing XML responses. I plan to rebuild this app from scratch using more modern techniques later this year.
