### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by TeamZaobi** [matthewpennell/eve-traders-handbook#26]
truly thx for ur marvelous works！

but， i ve followed all the " installation " , and have done all steps. 

but i got "No input file specified." on page since the symlink was created, it's not "404" nor anything more. 

 Since my php, mysql, nginx are all work well, i cant figure out what's happen, may i get ur help?

**Comment by TeamZaobi** [comment]
i ve already complete step 4, database staff. but i still got that page exactly.

**Comment by matthewpennell** [comment]
As per the **Important Note** in the first line of the README, this application currently does not work (since it relies on outdated tech). I'm planning to rebuild it at some point in the near future, so feel free to *Star* it to be notified of any changes.
