### ISSUE TITLE
Doesnt seem to work in the latest version of XAMPP

### ISSUE THREAD

**Issue by mgk0330** [matthewpennell/eve-traders-handbook#27]
Initially it complained about mycrypt not being available, which i was able to correct.  However i am not able to progress beyond the SQL setup because after setting the databases as described and restarting the machine, i still have the whoops... message.  It is unclear why this is the case.

**Comment by matthewpennell** [comment]
As per the note at the start of the README on the repository homepage, this application is effectively dead - it relies on an API that changed and was built using what is now fairly outdated libraries.

As I'm no longer playing the game, I don't have any plans to release any updates or new versions, sorry.
