### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by hiimk3v** [matthewpennell/eve-traders-handbook#28]
When trying to open the web application I get this message: 

Fatal error: Uncaught Error: Undefined constant "Patchwork\Utf8\MB_OVERLOAD_STRING" in C:\Users\altwa\Downloads\eve-traders-handbook\vendor\patchwork\utf8\class\Patchwork\Utf8\Bootup.php:47 Stack trace: #0 C:\Users\altwa\Downloads\eve-traders-handbook\bootstrap\autoload.php(46): Patchwork\Utf8\Bootup::initMbstring() #1 C:\Users\altwa\Downloads\eve-traders-handbook\public\index.php(21): require('C:\\Users\\altwa\\...') #2 {main} thrown in C:\Users\altwa\Downloads\eve-traders-handbook\vendor\patchwork\utf8\class\Patchwork\Utf8\Bootup.php on line 47

**Comment by matthewpennell** [comment]
@hiimk3v Sorry, this application is very much non-supported and non-working. I'm not even playing EVE any more.

You could check out some of the other tools listed here: https://github.com/devfleet/awesome-eve#market
