### ISSUE TITLE
[Question] Have you considered implementing some more real-time analytics?

### ISSUE THREAD

**Issue by jimmygle** [matthewpennell/eve-traders-handbook#3]
I've been toying with a similar app, but using the [EMDR](http://eve-market-data-relay.readthedocs.org/en/latest/index.html) feed for real-time market updates. The data is pretty intense (700+mb/day), but there could be some very interesting trends pulled from it.

If you're interested, I can share the Vagrant setup and code that I did my trial run with. It's a PHP script running a couple composer packages that uses their pub-sub feed. Incredible amounts of EVE market data from around the galaxy.

**Comment by matthewpennell** [comment]
I did originally plan to show market update data in the item details view, similar to the market trends tab in the in-game Market window, but I decided that pulling in and handling all that data was going to be too much work. I kind of envisioned that people would be using this app alongside playing the game, so they can manually check on the market activity of items.
