### ISSUE TITLE
getting Whoops, looks like something went wrong. PHP PDO issue?

### ISSUE THREAD

**Issue by arkham42** [matthewpennell/eve-traders-handbook#6]
Hey all. Running Fedoria on a virtual box. When I go to the webpage remotely (after doing  php artisan serv --host 192.168.1.10) I get the whoops error above.

Checking the logs, i see this:

[2015-05-11 17:09:04] production.ERROR: exception 'PDOException' with message 'could not find driver' in /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '<password>', Array)
#1 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(57): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(46): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(176): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2894): Illuminate\Database\DatabaseManager->connection(NULL)
#7 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2860): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1834): Illuminate\Database\Eloquent\Model->getConnection()
#9 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1750): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3081): Illuminate\Database\Eloquent\Model->newQuery()
#11 [internal function]: Illuminate\Database\Eloquent\Model->__call('where', Array)
#12 [internal function]: Filter->where('is_default', 1)
#13 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3097): call_user_func_array(Array, Array)
#14 /var/www/html/eve/app/controllers/MasterController.php(52): Illuminate\Database\Eloquent\Model::__callStatic('where', Array)
#15 /var/www/html/eve/app/controllers/MasterController.php(52): Filter::where('is_default', 1)
#16 [internal function]: MasterController->home()
#17 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#18 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('home', Array)
#19 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(MasterController), Object(Illuminate\Routing\Route), 'home')
#20 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'MasterControlle...', 'home')
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}()
#22 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#23 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#27 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#30 /var/www/html/eve/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#31 /var/www/html/eve/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#32 /var/www/html/eve/public/index.php(49): Illuminate\Foundation\Application->run()
#33 /var/www/html/eve/server.php(19): require_once('/var/www/html/e...')

Google isnt being much help. Any ideas?

**Comment by matthewpennell** [comment]
Does this help: http://stackoverflow.com/questions/22598906/exception-pdoexception-with-message-could-not-find-driver-sqlsrv-laravel-art

**Comment by matthewpennell** [comment]
Or this, which suggests you might not have the pdo_mysql driver installed: http://stackoverflow.com/questions/2852748/pdoexception-could-not-find-driver

**Comment by arkham42** [comment]
Ahh, that did it. 

yum install php-mysqlnd.i686 php-pear-MDB2-Driver-mysql.noarch php-pecl-mysqlnd-ms.i686
as i was not sure specifically which driver i needed. Its working now, thanks!
