### ISSUE TITLE
Request: Add shipment costs to calculations

### ISSUE THREAD

**Issue by arkham42** [matthewpennell/eve-traders-handbook#7]
A lot of people have to pay to ship items from the market hubs to the destination. Is it possible to add in fixed costs that multiply against the volume of the product as part of the determination for profitibility?

So for example, if i import something that is 100m3 and it costs 250 per m3 to ship, can it deduct the 250,000 from the calculations?

**Comment by matthewpennell** [comment]
Sure, that would be simple enough. I'll add a fixed amount you can edit in the Settings, and apply it to the import profit figures.

**Comment by matthewpennell** [comment]
Added shipping costs with 360dd888243aa69faa98371b8f49a5e635f351d3. It will also require a database update to pick up the shipping_cost field.
